Use older tox.
Seen on some other Zope packages as well.
Otherwise you may run into this error:

```
$ bin/buildout
Develop: '/Users/maurits/community/zope/Products.ZSQLMethods/.'
warning: no files found matching '*.txt'
warning: no previously-included files matching '*.pyo' found anywhere in distribution
Installing interpreter.
Getting distribution for 'tox'.
/Users/maurits/.pyenv/versions/3.8.1/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
warning: no files found matching 'CHANGELOG.rst'
warning: no files found matching 'README.rst'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
zip_safe flag not set; analyzing archive contents...
tox.__pycache__._pytestplugin.cpython-38: module references __file__
tox.__pycache__.constants.cpython-38: module references __file__
tox.config.__pycache__.__init__.cpython-38: module references __file__
tox.session.__pycache__.__init__.cpython-38: module references __file__
While:
  Installing interpreter.
  Getting distribution for 'tox'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/Users/maurits/shared-eggs/cp38/zc.recipe.egg-2.0.7-py3.8.egg/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
  File "/Users/maurits/shared-eggs/cp38/zc.recipe.egg-2.0.7-py3.8.egg/zc/recipe/egg/egg.py", line 78, in working_set
    ws = self._working_set(
  File "/Users/maurits/shared-eggs/cp38/zc.recipe.egg-2.0.7-py3.8.egg/zc/recipe/egg/egg.py", line 161, in _working_set
    ws = zc.buildout.easy_install.install(
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/easy_install.py", line 682, in install
    for dist in self._get_dist(requirement, ws):
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/easy_install.py", line 1776, in _move_to_eggs_dir_and_compile
    assert newdist is not None  # newloc above is missing our dist?!
AssertionError
```

And when you then run it a second time to see if that helps, the error changes because cruft is left behind:

```
$ bin/buildout
...
While:
  Installing interpreter.
  Getting distribution for 'tox'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/Users/maurits/shared-eggs/cp38/zc.recipe.egg-2.0.7-py3.8.egg/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
  File "/Users/maurits/shared-eggs/cp38/zc.recipe.egg-2.0.7-py3.8.egg/zc/recipe/egg/egg.py", line 78, in working_set
    ws = self._working_set(
  File "/Users/maurits/shared-eggs/cp38/zc.recipe.egg-2.0.7-py3.8.egg/zc/recipe/egg/egg.py", line 161, in _working_set
    ws = zc.buildout.easy_install.install(
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/easy_install.py", line 682, in install
    for dist in self._get_dist(requirement, ws):
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/Users/maurits/shared-eggs/cp38/zc.buildout-2.13.2-py3.8.egg/zc/buildout/easy_install.py", line 1750, in _move_to_eggs_dir_and_compile
    os.rename(tmp_loc, newloc)
OSError: [Errno 66] Directory not empty: '/Users/maurits/shared-eggs/cp38/tmprrfxnhqb/tox-0.0.0-py3.8.egg' -> '/Users/maurits/shared-eggs/cp38/tox-0.0.0-py3.8.egg'
```